apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: default

    receivers:
      - name: default
        slack_configs:
          - api_url: "YOUR_SLACK_WEBHOOK"
            channel: "#alerts"