apiVersion: apps/v1
kind: Deployment
metadata:
  name: grazyna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grazyna
  template:
    metadata:
      labels:
        app: grazyna
    spec:
      containers:
        - name: grazyna
          image: ghcr.io/wiciomalta-spec/grazyna:latest
          ports:
            - containerPort: 3000
